### ISSUE TITLE
Inventory Title Error

### ISSUE THREAD

**Issue by Eejit43** [Jikoo/OpenInv#20] opened 2021-05-02 18:09 UTC
Hello!
When viewing other player's inventory or enderchest, the title of the container is always (My IGN)'s Inventory/Ender Chest. It never titles the container properly. Is there a fix for this?

**Comment by Jikoo** [comment] 2021-05-02 22:20
Duplicate of #13

**Comment by Jikoo** [comment] 2021-05-02 22:20
You can grab dev builds out of the actions tab - select a run, download and unzip the dist file.

**Closed by Jikoo** 2021-05-02 22:20 UTC
