### ISSUE TITLE
[4.1.6] GUI title displays issuer's name rather than target's

### ISSUE THREAD

**Issue by Oaksworth** [Jikoo/OpenInv#21] opened 2021-05-07 22:40 UTC
Hello! I hope you are well.
Firstly, thanks a lot for maintaining OpenInv. I've been using it since 2014 and I always recommend it to others.

This is a very simple issue.

In the following example, **Oaksworth** is the command issuer and **fvsparkles** is the target.

When Oaksworth issues `/openinv fvsparkles`, the GUI title will be "Oaksworth's Inventory" instead of "fvsparkles's Inventory":

![2021-05-07_19 11 15](https://user-images.githubusercontent.com/46974852/117514320-ebf41180-af69-11eb-90c8-2971ebe7c8c0.png)

![2021-05-07_19 11 30](https://user-images.githubusercontent.com/46974852/117514329-f1515c00-af69-11eb-9763-97c6f4f8b0e5.png)

The same thing happens with `/openender fvsparkles`:

![2021-05-07_19 15 39](https://user-images.githubusercontent.com/46974852/117514369-07f7b300-af6a-11eb-8c3f-a6c2ba7dee81.png)

![2021-05-07_19 16 09](https://user-images.githubusercontent.com/46974852/117514377-0c23d080-af6a-11eb-8476-a507684d68db.png)

The intended behavior would be to display the target's name on inventories and ender chests.

Thanks in advance! :)

**Comment by Jikoo** [comment] 2021-05-07 23:12
Duplicate of #13

**Closed by Jikoo** 2021-05-07 23:12 UTC
