### ISSUE TITLE
Opening a shulker box that has a non solid block in the way with silent chest does the open shulker animation and the shulker doesn't close.

### ISSUE THREAD

**Issue by matthew2837** [Jikoo/OpenInv#36] opened 2021-07-24 18:48 UTC
https://user-images.githubusercontent.com/13020950/126878430-eba81ea5-49cd-4cd4-a376-70e7202a7bb3.mp4

**Comment by Jikoo** [comment] 2021-07-25 17:04
Please try without client mods installed. You've clearly got several things accessing inventories in that video.

**Comment by Jikoo** [comment] 2021-07-25 17:05
Also, include basic information like server version and OpenInv version.

**Comment by matthew2837** [comment] 2021-07-26 04:05
Open Inv Version 4.1.8, Paper MC 1.17.1 #124

https://user-images.githubusercontent.com/13020950/126931623-e0e15d90-8101-4298-98d8-5fc3faa93606.mp4

**Comment by Jikoo** [comment] 2021-07-26 11:59
Interesting, it's two "separate" issues. Upper slabs are considered blocking because the whole block is checked instead of just the lower half. Signs specifically internally report themselves as having an empty bounding box in this case, but I'm not sure yet why.

Slabs is an easy fix. Not sure how I want to approach signs. It feels like a regression to go back to using pure NMS for that part, but special cases will probably slip through the cracks if I don't.

**Closed** 2021-10-16 20:23 UTC
Labels: bug
