### ISSUE TITLE
Unable to open enderchest through /oe 

### ISSUE THREAD

**Issue by Acult** [Jikoo/OpenInv#204] opened 2024-06-03 17:20 UTC
Using minecraft 1.16.5 mohist, OpenInv 4.1.8

I'm unable to run the /oe command, while /oi works fine
https://pastebin.com/RVr3NY33

**Comment by Jikoo** [comment] 2024-06-04 04:40
Duplicate of #59

**Closed by Jikoo** 2024-06-04 04:40 UTC
