### ISSUE TITLE
openender chest in 1.19.1 crashes server

### ISSUE THREAD

**Issue by fahlur** [Jikoo/OpenInv#92] opened 2022-08-01 14:26 UTC
`2022-08-01 10:24:17,423 Server thread ERROR Recursive call to appender Async
[10:24:17 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'int net.minecraft.world.inventory.InventoryEnderChest.P_()'
        at com.lishid.openinv.internal.v1_19_R1.SpecialEnderChest.P_(SpecialEnderChest.java:131) ~[OpenInv.jar:?]
        at com.lishid.openinv.internal.v1_19_R1.SpecialEnderChest.a(SpecialEnderChest.java:244) ~[OpenInv.jar:?]
        at net.minecraft.world.inventory.Slot.set(Slot.java:59) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:861) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:761) ~[?:?]
        at net.minecraft.world.inventory.ChestMenu.quickMoveStack(ChestMenu.java:150) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftContainer.a(CraftContainer.java:309) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:538) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:381) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3378) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:24:17 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-08-01_10.24.17-server.txt`

**Comment by Doc94** [comment] 2022-08-01 15:58
i try with Paper latest and not see errors with `/openender MrDoc94`

**Comment by Jikoo** [comment] 2022-08-01 17:31
Duplicate of #91

**Closed by Jikoo** 2022-08-01 17:31 UTC

**Comment by fahlur** [comment] 2022-08-02 03:07
4.2.1 that was posted 9 hours ago fixed the issue it appears.
